package day15;

import java.util.Scanner;

public class Exception02 {

	public static void main(String[] args) {
		//try~catch문으로 예외처리
		//두 수, 연사자를 입력받아 4칙연산을 수행하고 결과를 리턴하는 메서드 생성		
		Scanner scan = new Scanner(System.in);
		System.out.println("숫자1를 입력해주세요.");
		int num1 = scan.nextInt();
		System.out.println("숫자2를 입력해주세요.");
		int num2 = scan.nextInt();
		System.out.println("연산자를 입력해주세요.");
		char op = scan.next().charAt(0);
		
		int a = num1+num2;
		int b = num1-num2;
		int c = num1*num2;
		double d = (double)num1/num2;
		int e = num1%num2;
		
		switch(op) {
		case '+': System.out.println(""+num1+op+num2+"="+a);
			break;
		case '-': System.out.println(""+num1+op+num2+"="+b);		
			break;
		case '*': System.out.println(""+num1+op+num2+"="+c);		
			break;
		case '/':  System.out.println(""+num1+op+num2+"="+d);	
			break;
		case '%': System.out.println(""+num1+op+num2+"="+e);		
			break;
			default:
				System.out.println("잘못된 입력~!!");			
		}
		scan.close();


	}	
}


	
	